/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    songs: Song;
    media: Media;
    audio: Audio;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    songs: SongsSelect<false> | SongsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    audio: AudioSelect<false> | AudioSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('it' | 'en') | ('it' | 'en')[];
  globals: {
    home: Home;
    contact: Contact;
    legals: Legal;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    legals: LegalsSelect<false> | LegalsSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: 'it' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The works shown on the landing page, in the order set below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs".
 */
export interface Song {
  id: number;
  title: string;
  /**
   * Left empty in English, the Italian text is shown instead.
   */
  story?: string | null;
  cover: number | Media;
  track: number | Audio;
  /**
   * Stored here so the page can show a running time without loading the audio.
   */
  durationSeconds: number;
  /**
   * Optional. Left empty, no link is shown.
   */
  platformUrl?: string | null;
  /**
   * Lowest first. Anna’s strongest work goes at the top.
   */
  order: number;
  reference?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio".
 */
export interface Audio {
  id: number;
  peaks?: number[];
  tone?: number[];
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'songs';
        value: number | Song;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audio';
        value: number | Audio;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "songs_select".
 */
export interface SongsSelect<T extends boolean = true> {
  title?: T;
  story?: T;
  cover?: T;
  track?: T;
  durationSeconds?: T;
  platformUrl?: T;
  order?: T;
  reference?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio_select".
 */
export interface AudioSelect<T extends boolean = true> {
  peaks?: T;
  tone?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    name: string;
    /**
     * What a Recruiter should know in the first two seconds.
     */
    tagline: string;
    portrait?: (number | null) | Media;
  };
  about?: {
    heading?: string | null;
    body?: string | null;
  };
  skills?: {
    heading?: string | null;
    entries?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
  };
  songs?: {
    heading?: string | null;
    intro?: string | null;
    listenLabel?: string | null;
    platformLabel?: string | null;
    pauseLabel?: string | null;
    /**
     * Read aloud by a screen reader; never shown.
     */
    seekLabel?: string | null;
  };
  timeline?: {
    heading?: string | null;
    /**
     * Names the scrollable strip for a screen reader; never shown.
     */
    scrollLabel?: string | null;
    entries?:
      | {
          /**
           * For example 2021–2024.
           */
          period: string;
          label: string;
          detail?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  contactCta?: {
    heading?: string | null;
    body?: string | null;
    buttonLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  heading?: string | null;
  intro?: string | null;
  form?: {
    /**
     * The black band above the form, and the name a screen reader gives it. Set edge to edge, so keep it short.
     */
    heading?: string | null;
    /**
     * Sits above the fields. All three are required.
     */
    requiredNote?: string | null;
    nameLabel?: string | null;
    emailLabel?: string | null;
    messageLabel?: string | null;
    submitLabel?: string | null;
    sendingLabel?: string | null;
    /**
     * Names the Cloudflare box, which is the one object on this site drawn by somebody else.
     */
    checkLabel?: string | null;
    /**
     * Shown when the check is what stopped the message. Without it the form says "check the fields marked" with nothing marked.
     */
    checkNote?: string | null;
    /**
     * Shown under a field that was left empty.
     */
    missingNote?: string | null;
    /**
     * Shown under an address that could not receive a reply.
     */
    emailNote?: string | null;
    /**
     * Beside the send button. The form stores nothing (ADR-0005) and that is worth saying here, not only on the legals page.
     */
    privacyNote?: string | null;
  };
  brief?: {
    heading?: string | null;
    intro?: string | null;
    /**
     * What a first message should carry so it can be answered rather than queried.
     */
    points?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  practical?: {
    heading?: string | null;
    /**
     * Short, checkable facts. Nothing with a date in it: a claim that rots is worse than no claim.
     */
    entries?:
      | {
          /**
           * Printed on the card’s tab, so two or three words at most.
           */
          term: string;
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  direct?: {
    heading?: string | null;
    /**
     * The address comes from Settings, not from here. This block renders nothing while that field is empty.
     */
    note?: string | null;
    /**
     * Heads the links from Settings, repeated on the page at a readable size.
     */
    elsewhereHeading?: string | null;
  };
  outcome?: {
    success?: string | null;
    failure?: string | null;
    invalid?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legals".
 */
export interface Legal {
  id: number;
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  contactEmail?: string | null;
  socialLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  legalsLinkLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        name?: T;
        tagline?: T;
        portrait?: T;
      };
  about?:
    | T
    | {
        heading?: T;
        body?: T;
      };
  skills?:
    | T
    | {
        heading?: T;
        entries?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  songs?:
    | T
    | {
        heading?: T;
        intro?: T;
        listenLabel?: T;
        platformLabel?: T;
        pauseLabel?: T;
        seekLabel?: T;
      };
  timeline?:
    | T
    | {
        heading?: T;
        scrollLabel?: T;
        entries?:
          | T
          | {
              period?: T;
              label?: T;
              detail?: T;
              id?: T;
            };
      };
  contactCta?:
    | T
    | {
        heading?: T;
        body?: T;
        buttonLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  form?:
    | T
    | {
        heading?: T;
        requiredNote?: T;
        nameLabel?: T;
        emailLabel?: T;
        messageLabel?: T;
        submitLabel?: T;
        sendingLabel?: T;
        checkLabel?: T;
        checkNote?: T;
        missingNote?: T;
        emailNote?: T;
        privacyNote?: T;
      };
  brief?:
    | T
    | {
        heading?: T;
        intro?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  practical?:
    | T
    | {
        heading?: T;
        entries?:
          | T
          | {
              term?: T;
              value?: T;
              id?: T;
            };
      };
  direct?:
    | T
    | {
        heading?: T;
        note?: T;
        elsewhereHeading?: T;
      };
  outcome?:
    | T
    | {
        success?: T;
        failure?: T;
        invalid?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legals_select".
 */
export interface LegalsSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  contactEmail?: T;
  socialLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  legalsLinkLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}